---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../../lib/nncp

patches:
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-0
    patch: &ctlplanevrf_template |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: ctlplane VRF
          name: ospbrvrf
          type: vrf
          state: up
          vrf:
            port:
              - ospbr
            route-table-id: 20

  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-1
    patch: *ctlplanevrf_template

  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-2
    patch: *ctlplanevrf_template

  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-0
    patch: &routes |-
      - op: add
        path: /spec/desiredState/routes/config/-
        value:
          destination: 0.0.0.0/0
          metric: 150
          next-hop-address: _replaced_
          next-hop-interface: ospbr
          table-id: 20

  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-1
    patch: *routes

  - target:
      kind: NodeNetworkConfigurationPolicy
      name: master-2
    patch: *routes

replacements:

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.subnets.0.gateway
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-0
        fieldPaths:
          - spec.desiredState.routes.config.0.next-hop-address
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-1
        fieldPaths:
          - spec.desiredState.routes.config.0.next-hop-address
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: master-2
        fieldPaths:
          - spec.desiredState.routes.config.0.next-hop-address

