---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - dataplane-ssh-secret.yaml
  - nova-migration-ssh-secret.yaml

secretGenerator:
  - name: libvirt-secret
    behavior: create
    literals:
      - LibvirtPassword=12345678
    options:
      disableNameSuffixHash: true

# OpenStackDataPlaneNodeSet customizations
replacements:
  # Dataplane SSH access secret customizations
  - source:
      kind: ConfigMap
      name: dataplane-secret-values
      fieldPath: data.ssh_keys.authorized
    targets:
      - select:
          kind: Secret
          name: dataplane-ansible-ssh-private-key-secret
        fieldPaths:
          - data.authorized_keys
        options:
          create: true
  - source:
      kind: ConfigMap
      name: dataplane-secret-values
      fieldPath: data.ssh_keys.private
    targets:
      - select:
          kind: Secret
          name: dataplane-ansible-ssh-private-key-secret
        fieldPaths:
          - data.ssh-privatekey
        options:
          create: true
  - source:
      kind: ConfigMap
      name: dataplane-secret-values
      fieldPath: data.ssh_keys.public
    targets:
      - select:
          kind: Secret
          name: dataplane-ansible-ssh-private-key-secret
        fieldPaths:
          - data.ssh-publickey
        options:
          create: true

  # Nova migration secret customizations
  - source:
      kind: ConfigMap
      name: dataplane-secret-values
      fieldPath: data.nova.migration.ssh_keys.private
    targets:
      - select:
          kind: Secret
          name: nova-migration-ssh-key
        fieldPaths:
          - data.ssh-privatekey
        options:
          create: true
  - source:
      kind: ConfigMap
      name: dataplane-secret-values
      fieldPath: data.nova.migration.ssh_keys.public
    targets:
      - select:
          kind: Secret
          name: nova-migration-ssh-key
        fieldPaths:
          - data.ssh-publickey
        options:
          create: true
