---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  horizon:
    enabled: false
  rabbitmq:
    replicas: 1
    erlangInetConfig: |
      {inet6, true}.
    envConfig: |
      SERVER_ADDITIONAL_ERL_ARGS="-kernel inetrc '/etc/rabbitmq/erl_inetrc'  -proto_dist inet6_tcp"
      RABBITMQ_CTL_ERL_ARGS="-proto_dist inet6_tcp"
  galera:
    replicas: 1
  ironic:
    enabled: true
    ironicConductors:
      - customServiceConfig: |
          [neutron]
          cleaning_network = provisioning
          provisioning_network = provisioning
          rescuing_network = provisioning
  nova:
    cellTemplates:
      cell0:
        cellDatabaseInstance: openstack
        cellDatabaseAccount: nova-cell0
        cellMessageBusInstance: rabbitmq
        hasAPIAccess: true
      cell1:
        cellDatabaseInstance: openstack-cell1
        cellDatabaseAccount: nova-cell1
        cellMessageBusInstance: rabbitmq-cell1
        hasAPIAccess: true
        novaComputeTemplates:
          compute-ironic:
            computeDriver: ironic.IronicDriver
