apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: deployment-post-ceph
  namespace: openstack
spec:
  nodeSets:
  - openstack-edpm-one
  - openstack-edpm-two
  servicesOverride:
    - ceph-client
    - ovn
    - neutron-metadata
    - libvirt
    - nova-custom-ceph
